### ISSUE TITLE
Add consts

### ISSUE THREAD

**Issue by IanaKhitsko** [znycheporuk/EuroDiffusion#1]
https://github.com/znycheporuk/EuroDiffusion/blob/23abde52be669fe44e880c3db15c8838848455cd/src/City.ts#L17

as well for 1000, 10 etc

**Comment by znycheporuk** [comment]
[done](https://github.com/znycheporuk/EuroDiffusion/commit/98b4ef4db5918823f3d05aa71787de360ea19b7d)
