### ISSUE TITLE
Move the method out of here

### ISSUE THREAD

**Issue by IanaKhitsko** [znycheporuk/EuroDiffusion#2]
https://github.com/znycheporuk/EuroDiffusion/blob/23abde52be669fe44e880c3db15c8838848455cd/src/World.ts#L35

Why cant we move this method out of here, name it smth like initiateNeighbors (or whatever) and call it directly from index.ts before the main cycle?

**Comment by znycheporuk** [comment]
[done](https://github.com/znycheporuk/EuroDiffusion/commit/dcb55a98215abb3d30170892c21df9010785c884)
