### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by IanaKhitsko** [znycheporuk/EuroDiffusion#3]
https://github.com/znycheporuk/EuroDiffusion/blob/23abde52be669fe44e880c3db15c8838848455cd/src/World.ts#L69

Looks like some hidden code duplication. Can you make some function/method with adding neighbors and passing the coordinates?

**Comment by znycheporuk** [comment]
fixed in this [commit](https://github.com/znycheporuk/EuroDiffusion/commit/677527214ae6af628b51ddb360afcc0d4db1be04)

**Comment by znycheporuk** [comment]
simplified to extreme in [commit](https://github.com/znycheporuk/EuroDiffusion/commit/cf6851bfad974a30a45ec9a4f509d4b0558dc0d4)
