### ISSUE TITLE
Use hasOwnProperty for checking if a property exists

### ISSUE THREAD

**Issue by vladyslavmortikov** [znycheporuk/EuroDiffusion#4]
https://github.com/znycheporuk/EuroDiffusion/blob/98b4ef4db5918823f3d05aa71787de360ea19b7d/src/City.ts#L33

To avoid any potential problems with inherited properties, it's best to use the `hasOwnProperty` method when checking if a property exists within the receiveMoney and sendMoney methods. This way, only the object's own properties will be accessed.

```
receiveMoney(transfer: Transfer) {
  for (let countryName in transfer) {
    if (transfer.hasOwnProperty(countryName)) {
      this.balance[countryName] = (this.balance[countryName] || 0) + transfer[countryName];
    }
  }
}

sendMoney(transfer: Transfer) {
  for (let countryName in transfer) {
    if (transfer.hasOwnProperty(countryName)) {
      this.balance[countryName] -= transfer[countryName];
    }
  }
}
```

What do you think on it?

**Comment by znycheporuk** [comment]
this is very unlikely can be an issue, as transfers are created in the same class where they are consumed, but potentially someone can really screw up the prototype, so I added safeguard you proposed in this [commit](https://github.com/znycheporuk/EuroDiffusion/commit/797ceb3b9cd9ce685f2852ffc04b870142a13e29)
