### ISSUE TITLE
Consider using a more descriptive method name for createCities

### ISSUE THREAD

**Issue by vladyslavmortikov** [znycheporuk/EuroDiffusion#5]
https://github.com/znycheporuk/EuroDiffusion/blob/98b4ef4db5918823f3d05aa71787de360ea19b7d/src/Country.ts#L14

The `createCities` method could be renamed to something like `generateCities` or `populateCities` to better reflect its purpose.

**Comment by znycheporuk** [comment]
[done](https://github.com/znycheporuk/EuroDiffusion/commit/cac2ec7b4f011976ef97f69ef52c7e75f39ad11d)
